apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vcfo-postgres
spec:
  serviceName: vcfo-postgres
  replicas: 1
  selector:
    matchLabels:
      app: vcfo-postgres
  template:
    metadata:
      labels:
        app: vcfo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: vcfo
